In [1]:
import sys
sys.path.append('/mnt/lovit/git/synthetic_dataset/')
import soydata

In [2]:
from soydata.visualize import ipython_2d_scatter
from soydata.data import get_decision_tree_data_1
from soydata.data import get_decision_tree_data_2

In [8]:
X_1, y_1 = get_decision_tree_data_1(n_samples=2000)
# ipython_2d_scatter(X_1, y_1, marker_size=5, height=1000, width=1000, title='Synthetic dataset 1')

In [10]:
X_2, y_2 = get_decision_tree_data_2(n_samples=2000)
# ipython_2d_scatter(X_2, y_2, marker_size=5, height=1000, width=1000, title='Synthetic dataset 2')

In [17]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier

# for depth in [1, 2, 3, 5, 10]:
for depth in [6]:
    dt = DecisionTreeClassifier(max_depth=depth, random_state=42)
    dt.fit(X_1, y_1)
    y_1_pred = dt.predict(X_1)

    error = y_1_pred - y_1
    correct = np.zeros(X_1.shape[0]).reshape(-1)
    correct[np.where(error == 0)[0]] = 1
    
    accuracy = correct.sum() / X_1.shape[0]
    print('dept = {}, accuracy = {}'.format(depth, accuracy))

#     ipython_2d_scatter(X_1, y_1_pred, height=1000, marker_size=5, width=1000, title='Synthetic dataset 1 prediction with\ndepth = {}, accoracy={}'.format(depth, accuracy))

dept = 6, accuracy = 1.0


In [102]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier

for depth in [4, 6, 9]:
    dt = DecisionTreeClassifier(max_depth=depth, random_state=42)
    dt.fit(X_2, y_2)
    y_2_pred = dt.predict(X_2)

    error = y_2_pred - y_2
    correct = np.zeros(X_2.shape[0]).reshape(-1)
    correct[np.where(error == 0)[0]] = 1
    
    accuracy = correct.sum() / X_2.shape[0]
    print('dept = {}, accuracy = {}'.format(depth, accuracy))

#     ipython_2d_scatter(X_2, y_2_pred, height=1000, marker_size=5, width=1000, title='Synthetic dataset 2 prediction with\ndepth = {}, accoracy={}'.format(depth, accuracy))

dept = 4, accuracy = 0.9107676969092722
dept = 6, accuracy = 0.9760717846460618
dept = 9, accuracy = 0.9990029910269193


In [28]:
# https://stackoverflow.com/questions/20224526/how-to-extract-the-decision-rules-from-scikit-learn-decision-tree?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

def get_lineage(tree, feature_names):
    left      = tree.tree_.children_left
    right     = tree.tree_.children_right
    threshold = tree.tree_.threshold
    features  = [feature_names[i] for i in tree.tree_.feature]
    # get ids of child nodes
    idx = np.argwhere(left == -1)[:,0]     
    def recurse(left, right, child, lineage=None):          
        if lineage is None:
            lineage = [child]
        if child in left:
            parent = np.where(left == child)[0].item()
            split = 'l'
        else:
            parent = np.where(right == child)[0].item()
            split = 'r'
        lineage.append((parent, split, threshold[parent], features[parent]))
        if parent == 0:
            lineage.reverse()
            return lineage
        else:
            return recurse(left, right, parent, lineage)
    for child in idx:
        for node in recurse(left, right, child):
            print (node)

In [31]:
# get_lineage(dt, ['x', 'y'])

In [22]:
left      = dt.tree_.children_left
right     = dt.tree_.children_right
threshold = dt.tree_.threshold

In [24]:
left.shape

(59,)

In [25]:
right.shape

(59,)

In [26]:
threshold.shape

(59,)

In [27]:
left

array([ 1,  2, -1,  4, -1, -1,  7, -1,  9, 10, 11, 12, 13, -1, -1, -1, -1,
       18, 19, 20, -1, 22, 23, -1, -1, -1, 27, 28, -1, 30, -1, -1, -1, 34,
       35, 36, 37, -1, -1, -1, -1, 42, 43, 44, -1, -1, -1, 48, 49, -1, -1,
       52, -1, -1, 55, -1, 57, -1, -1])

In [28]:
right

array([ 6,  3, -1,  5, -1, -1,  8, -1, 54, 17, 16, 15, 14, -1, -1, -1, -1,
       33, 26, 21, -1, 25, 24, -1, -1, -1, 32, 29, -1, 31, -1, -1, -1, 41,
       40, 39, 38, -1, -1, -1, -1, 47, 46, 45, -1, -1, -1, 51, 50, -1, -1,
       53, -1, -1, 56, -1, 58, -1, -1])

In [29]:
threshold

array([ 4.00539017,  7.00503731, -2.        ,  3.49398017, -2.        ,
       -2.        ,  2.00174618, -2.        ,  6.98615742,  4.36656189,
        4.98681259,  3.27961016,  4.26769447, -2.        , -2.        ,
       -2.        , -2.        ,  4.8539381 ,  7.30683231,  6.99763584,
       -2.        ,  4.68205166,  7.00949955, -2.        , -2.        ,
       -2.        ,  7.4809618 ,  7.38458014, -2.        ,  4.61641979,
       -2.        , -2.        , -2.        ,  5.66478252,  5.6269908 ,
        4.47982836,  5.11054134, -2.        , -2.        , -2.        ,
       -2.        ,  6.48954964,  5.00303268,  7.36141872, -2.        ,
       -2.        , -2.        ,  7.06216717,  6.63848925, -2.        ,
       -2.        ,  7.27605534, -2.        , -2.        ,  8.00331211,
       -2.        ,  8.01910591, -2.        , -2.        ])

In [30]:
dt.tree_.feature

array([ 1,  0, -2,  1, -2, -2,  0, -2,  1,  0,  1,  0,  1, -2, -2, -2, -2,
        1,  0,  0, -2,  1,  0, -2, -2, -2,  0,  0, -2,  1, -2, -2, -2,  0,
        1,  0,  1, -2, -2, -2, -2,  1,  1,  0, -2, -2, -2,  0,  0, -2, -2,
        0, -2, -2,  0, -2,  1, -2, -2])

In [49]:
features = ['x{}'.format(feature) if feature >= 0 else None for feature in dt.tree_.feature]

In [50]:
print(features)

['x1', 'x0', None, 'x1', None, None, 'x0', None, 'x1', 'x0', 'x1', 'x0', 'x1', None, None, None, None, 'x1', 'x0', 'x0', None, 'x1', 'x0', None, None, None, 'x0', 'x0', None, 'x1', None, None, None, 'x0', 'x1', 'x0', 'x1', None, None, None, None, 'x1', 'x1', 'x0', None, None, None, 'x0', 'x0', None, None, 'x0', None, None, 'x0', None, 'x1', None, None]


In [103]:
print(dt.tree_.value.shape)

(59, 1, 2)


In [35]:
dt.tree_.value[0]

array([[1045.,  961.]])

In [38]:
prob = np.asarray([freq/freq.sum() for freq in dt.tree_.value])

In [44]:
prob[0]

array([[0.52093719, 0.47906281]])

In [54]:
labels = np.asarray([prob_.argmax() for prob_ in prob])
labels

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1])

In [32]:
np.argwhere(left == -1)[:,0]

array([ 2,  4,  5,  7, 13, 14, 15, 16, 20, 23, 24, 25, 28, 30, 31, 32, 37,
       38, 39, 40, 44, 45, 46, 49, 50, 52, 53, 55, 57, 58])

In [52]:
l = [i for i in range(5)]

In [67]:
prob[0]

array([[0.52093719, 0.47906281]])

In [70]:
for p in prob[0][0]:
    print(p)

0.5209371884346959
0.4790628115653041


In [108]:
def print_tree_traversal(dt, feature_names=None, indent=4):
    left = dt.tree_.children_left
    right = dt.tree_.children_right
    threshold = dt.tree_.threshold
    if feature_names:
        features = [feature_names[f] if f >= 0 else None for f in dt.tree_.feature]
    else:
        features = ['x{}'.format(f) if f >= 0 else None for f in dt.tree_.feature]
    size = np.asarray([freq.sum() for freq in dt.tree_.value], dtype=np.int)
    prob = np.asarray([freq/freq.sum() for freq in dt.tree_.value])
    labels = np.asarray([prob_.argmax() for prob_ in prob])
    _print_tree_traversal(left, right, features, threshold, labels, size, prob, indent)

def _print_tree_traversal(left, right, features, threshold, labels, size, prob, indent=4):

    def is_leaf(i):
        return features[i] is None

    def print_status(i, depth, equation):
        message = '{} ({}). label={} n_samples={}, prob=({})'.format(
            '|--- ' * depth, # indention
            equation,        # equation
            labels[i],       # label
            size[i],         # n samples
            ', '.join(['%.3f' % float(p) for p in prob[i][0]])) # prob
        print(message, flush=True)

    def make_stack_item(idx, depth):
        # (child idx, depth, equation)
        items = [
            (right[idx], depth, '{} > {}'.format(features[idx], '%.3f'%threshold[idx])),
            (left[idx], depth, '{} < {}'.format(features[idx], '%.3f'%threshold[idx]))
        ]
        return items

    # initialize
    stack = make_stack_item(idx=0, depth=1)

    # print root
    print('Root n_samples={}, prob=({})'.format(
        size[0], ', '.join(['%.3f' % float(p) for p in prob[0][0]])))

    # while stack is not empty
    while stack:
        idx, depth, equation = stack.pop()
        # if node is leaf print status        
        if is_leaf(idx):
            print_status(idx, depth, equation)
        # else print status and add children (left, right) order
        else:
            print_status(idx, depth, equation)
            stack += make_stack_item(idx, depth+1)

#_print_tree_traversal(left, right, features, threshold, labels, prob)
print_tree_traversal(dt)

Root n_samples=2006, prob=(0.521, 0.479)
|---  (x1 < 4.005). label=1 n_samples=824, prob=(0.220, 0.780)
|--- |---  (x0 < 7.005). label=1 n_samples=612, prob=(0.000, 1.000)
|--- |---  (x0 > 7.005). label=0 n_samples=212, prob=(0.854, 0.146)
|--- |--- |---  (x1 < 3.494). label=0 n_samples=181, prob=(1.000, 0.000)
|--- |--- |---  (x1 > 3.494). label=1 n_samples=31, prob=(0.000, 1.000)
|---  (x1 > 4.005). label=0 n_samples=1182, prob=(0.731, 0.269)
|--- |---  (x0 < 2.002). label=0 n_samples=229, prob=(1.000, 0.000)
|--- |---  (x0 > 2.002). label=0 n_samples=953, prob=(0.666, 0.334)
|--- |--- |---  (x1 < 6.986). label=0 n_samples=474, prob=(0.511, 0.489)
|--- |--- |--- |---  (x0 < 4.367). label=1 n_samples=135, prob=(0.141, 0.859)
|--- |--- |--- |--- |---  (x1 < 4.987). label=0 n_samples=31, prob=(0.613, 0.387)
|--- |--- |--- |--- |--- |---  (x0 < 3.280). label=1 n_samples=17, prob=(0.294, 0.706)
|--- |--- |--- |--- |--- |--- |---  (x1 < 4.268). label=0 n_samples=5, prob=(1.000, 0.000)
|---

In [107]:
print_tree_traversal(dt, feature_names=['var1', 'var2'], indent=8)

|--- Root n_samples=2006, prob=(0.521, 0.479)
|---  (var2 < 4.005). label=1 n_samples=824, prob=(0.220, 0.780)
|--- |---  (var1 < 7.005). label=1 n_samples=612, prob=(0.000, 1.000)
|--- |---  (var1 > 7.005). label=0 n_samples=212, prob=(0.854, 0.146)
|--- |--- |---  (var2 < 3.494). label=0 n_samples=181, prob=(1.000, 0.000)
|--- |--- |---  (var2 > 3.494). label=1 n_samples=31, prob=(0.000, 1.000)
|---  (var2 > 4.005). label=0 n_samples=1182, prob=(0.731, 0.269)
|--- |---  (var1 < 2.002). label=0 n_samples=229, prob=(1.000, 0.000)
|--- |---  (var1 > 2.002). label=0 n_samples=953, prob=(0.666, 0.334)
|--- |--- |---  (var2 < 6.986). label=0 n_samples=474, prob=(0.511, 0.489)
|--- |--- |--- |---  (var1 < 4.367). label=1 n_samples=135, prob=(0.141, 0.859)
|--- |--- |--- |--- |---  (var2 < 4.987). label=0 n_samples=31, prob=(0.613, 0.387)
|--- |--- |--- |--- |--- |---  (var1 < 3.280). label=1 n_samples=17, prob=(0.294, 0.706)
|--- |--- |--- |--- |--- |--- |---  (var2 < 4.268). label=0 n_samp