In [1]:
import pickle
with open('/mnt/lovit/works/fastcampus_text_deeplearning/5th/data/corpus_10days/models/params_keywords', 'rb') as f:
    params = pickle.load(f)
print(params.keys())

dict_keys(['x', 'word2index', 'index2word'])


In [2]:
X = params['x']
idx2vocab = params['index2word']
vocab2idx = params['word2index']

In [4]:
print(X.shape) # (30091, 9774)
print(vocab2idx['아이오아이']) # 5537

(30091, 9774)
5537


In [6]:
csr_matrix?

In [7]:
from scipy.sparse import csr_matrix

rows, cols = X.nonzero()
data = X.data

# Create X_. tf matrix that dosen't have term '아이오아이'
rows_, cols_, data_ = [], [], []
for r, c, d in zip(rows, cols, data):
    if c == 5537:
        continue
    rows_.append(r)
    cols_.append(c)
    data_.append(d)
X_ = csr_matrix((data_, (rows_, cols_)))

# Create Y. 1 if a doc has '아이오아이' term else 0
pos_set = set(X[:,5537].nonzero()[0]) 
Y = [1 if r in pos_set else 0 for r in range(X.shape[0])]

In [10]:
print('number of positive docs = {}'.format(len(pos_set)))
print('nonzero elements: {} -> {}'.format(X.nnz, X_.nnz))

number of positive docs = 97
nonzero elements: 1934111 -> 1934014


In [12]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression(penalty='l1')
logistic.fit(X_, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [14]:
coef = logistic.coef_.reshape(-1)
print(coef.shape)

(9774,)


In [21]:
for vocab_idx, w in sorted(enumerate(coef), key=lambda x:-x[1])[:100]:
    if w <= 0:
        break
    print(idx2vocab[vocab_idx], end=' ')

너무너무너무 선의 산들 엠카운트다운 챔피언 사나 드림 뮤직 먹고 완전체 일산 세련 같이 뉴스1스타 컴백 소속사 곡으로 보컬 열창 만나게 인사 마무리 박진영 선보 무대 수출 서울신문 활동 다이아 유정 인기 매력 등장 카메라 개인 고양시 비타민 수준 멤버들 걸그룹 한편 1위 예능 순위 세븐 발매 야구 불독 다비치 파워풀 이날 걸크러쉬 신용재 화려 프로듀스101 반전 일간스포츠 프로그램 스마트폰 트와이스 키미 일산동구 프로듀스 기자 

## regression regularization

In [40]:
X**2

array([[  0.  ],
       [  1.  ],
       [  1.21],
       [  9.  ],
       [ 30.25],
       [ 32.49],
       [ 49.  ],
       [ 81.  ]])

In [44]:
import numpy as np
Y = np.asarray([1, 2, 3, 2.2, 4, 4.5, 3.2, 6]).reshape(-1,1)
X = np.asarray([0, 1, 1.1, 3, 5.5, 5.7, 7, 9]).reshape(-1,1)
X_ = np.concatenate((X ** 2, X ** 3, np.sqrt(X)), axis=1)

In [45]:
X_.shape

(8, 3)

In [46]:
from sklearn.linear_model import Ridge

regression = Ridge(alpha=0.0, fit_intercept=False)
regression.fit(X_, Y)

Ridge(alpha=0.0, copy_X=True, fit_intercept=False, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [48]:
regression.predict(X_)

array([[ 0.        ],
       [ 2.18007342],
       [ 2.26875011],
       [ 3.14427867],
       [ 3.58327988],
       [ 3.6332599 ],
       [ 4.13477447],
       [ 5.84158582]])

In [49]:
regression.coef_

array([[-0.13340119,  0.01337005,  2.30010455]])